apiVersion: v1
kind: ServiceAccount
metadata:
  name: diffsnap-controller
  namespace: diffsnap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffsnap-controller
  namespace: diffsnap
  labels:
    app: diffsnap
    role: controller
spec:
  selector:
    matchLabels:
      app: diffsnap
      role: controller
  template:
    metadata:
      labels:
        app: diffsnap
        role: controller
    spec:
      serviceAccountName: diffsnap-controller
      containers:
      - name: controller
        image: quay.io/isim/diffsnap-controller:latest
        imagePullPolicy: Always
        command: ["/bin/diffsnap-controller"]
