kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: diffsnap-controller
rules:
- apiGroups: ["differentialsnapshot.example.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: diffsnap-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diffsnap-controller
subjects:
- kind: ServiceAccount
  name: diffsnap-controller
  namespace: diffsnap
