apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi
  labels:
    app: diffsnap
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ebs-csi
  labels:
    app: diffsnap
driver: ebs.csi.aws.com
deletionPolicy: Delete
