apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volsnapdelta-client-role
rules:
- nonResourceURLs: ["/*"]
  verbs: ["get"]
- apiGroups: ["differentialsnapshot.example.com"]
  resources:
  - volumesnapshotdeltas
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volsnapdelta-client-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volsnapdelta-client-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
