apiVersion: v1
kind: Pod
metadata:
  name: test-curl
spec:
  containers:
  - name: test-curl
    image: quay.io/brancz/krp-curl:v0.0.2
    command:
    - sh
    - -c
    - tail -f /dev/null
  restartPolicy: Never
