kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testns:cluster-role
  labels:
    app.kubernetes.io/part-of: example.com
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "create", "get" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "create", "get", "list", "update", "watch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes" ]
    verbs: [ "get", "delete", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "create", "get", "update", "list" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotclasses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshots" ]
    verbs: [ "create", "get", "list", "watch", "delete" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotcontents" ]
    verbs: [ "create", "get", "list", "watch", "delete" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testns:cluster-role-binding
  labels:
    app.kubernetes.io/part-of: example.com
subjects:
  - kind: ServiceAccount
    name: default
    namespace: testns
roleRef:
  kind: ClusterRole
  name: testns:cluster-role
  apiGroup: rbac.authorization.k8s.io
---
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testnsrole
  namespace: testns
  labels:
    app.kubernetes.io/part-of: example.com
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testnsrolebinding
  namespace: testns
  labels:
    app.kubernetes.io/part-of: example.com
roleRef:
  kind: Role
  name: testnsrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: testns