kind: Pod
apiVersion: v1
metadata:
  name: phtest
  namespace: testns
spec:
  containers:
    - name: ph-testpod
      args:
           - -c
           - while true; do echo hello; sleep 10;done
      command:
           - /bin/sh
      image: ubuntu
      imagePullPolicy: IfNotPresent
